//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Race_timer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EventTypeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventTypeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Race_timer.Resources.EventTypeResource", typeof(EventTypeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquathlon.
        /// </summary>
        public static string Aquathlon {
            get {
                return ResourceManager.GetString("Aquathlon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athletics.
        /// </summary>
        public static string Athletics {
            get {
                return ResourceManager.GetString("Athletics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biathlon.
        /// </summary>
        public static string Biathlon {
            get {
                return ResourceManager.GetString("Biathlon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bike Tour.
        /// </summary>
        public static string BikeTour {
            get {
                return ResourceManager.GetString("BikeTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMX.
        /// </summary>
        public static string BMX {
            get {
                return ResourceManager.GetString("BMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canicross.
        /// </summary>
        public static string Canicross {
            get {
                return ResourceManager.GetString("Canicross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Country Skiing.
        /// </summary>
        public static string CrossCountrySkiing {
            get {
                return ResourceManager.GetString("CrossCountrySkiing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycling.
        /// </summary>
        public static string Cycling {
            get {
                return ResourceManager.GetString("Cycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclocross.
        /// </summary>
        public static string Cyclocross {
            get {
                return ResourceManager.GetString("Cyclocross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duathlon.
        /// </summary>
        public static string Duathlon {
            get {
                return ResourceManager.GetString("Duathlon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equestrian.
        /// </summary>
        public static string Equestrian {
            get {
                return ResourceManager.GetString("Equestrian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigathlon.
        /// </summary>
        public static string Gigathlon {
            get {
                return ResourceManager.GetString("Gigathlon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline.
        /// </summary>
        public static string Inline {
            get {
                return ResourceManager.GetString("Inline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayak.
        /// </summary>
        public static string Kayak {
            get {
                return ResourceManager.GetString("Kayak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motocross.
        /// </summary>
        public static string Motocross {
            get {
                return ResourceManager.GetString("Motocross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorsports.
        /// </summary>
        public static string Motorsports {
            get {
                return ResourceManager.GetString("Motorsports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain Bike.
        /// </summary>
        public static string MountainBike {
            get {
                return ResourceManager.GetString("MountainBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obstacle Course Race.
        /// </summary>
        public static string ObstacleCourseRace {
            get {
                return ResourceManager.GetString("ObstacleCourseRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rowing.
        /// </summary>
        public static string Rowing {
            get {
                return ResourceManager.GetString("Rowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sailing.
        /// </summary>
        public static string Sailing {
            get {
                return ResourceManager.GetString("Sailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skiing.
        /// </summary>
        public static string Skiing {
            get {
                return ResourceManager.GetString("Skiing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ski Mountaineering.
        /// </summary>
        public static string SkiMountaineering {
            get {
                return ResourceManager.GetString("SkiMountaineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky Run.
        /// </summary>
        public static string SkyRun {
            get {
                return ResourceManager.GetString("SkyRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sled Dog.
        /// </summary>
        public static string SledDog {
            get {
                return ResourceManager.GetString("SledDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snowboard.
        /// </summary>
        public static string Snowboard {
            get {
                return ResourceManager.GetString("Snowboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Skating.
        /// </summary>
        public static string SpeedSkating {
            get {
                return ResourceManager.GetString("SpeedSkating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand-up Paddleboarding.
        /// </summary>
        public static string StandupPaddleboarding {
            get {
                return ResourceManager.GetString("StandupPaddleboarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swimming.
        /// </summary>
        public static string Swimming {
            get {
                return ResourceManager.GetString("Swimming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trail Running.
        /// </summary>
        public static string TrialRunning {
            get {
                return ResourceManager.GetString("TrialRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triathlon.
        /// </summary>
        public static string Triathlon {
            get {
                return ResourceManager.GetString("Triathlon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wakeboard.
        /// </summary>
        public static string Wakeboard {
            get {
                return ResourceManager.GetString("Wakeboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking.
        /// </summary>
        public static string Walking {
            get {
                return ResourceManager.GetString("Walking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Skiing.
        /// </summary>
        public static string WaterSkiing {
            get {
                return ResourceManager.GetString("WaterSkiing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women&apos;s Run.
        /// </summary>
        public static string WomensRun {
            get {
                return ResourceManager.GetString("WomensRun", resourceCulture);
            }
        }
    }
}
